### ISSUE TITLE
UniProt.ws lookup fails on some valid UniProt IDs

### ISSUE THREAD

**Issue by ghost** [Bioconductor/UniProt.ws#11]
Consider the following query:

up.ws <- UniProt.ws::UniProt.ws(taxId=9606)
res <- UniProt.ws::select(x=up.ws, keys=c("HGNC:417", "HGNC:30235", "HGNC:19732", "HGNC:51504","HGNC:51514","HGNC:51513"), columns="ENSEMBL", keytype="HGNC")

Using version 2.22.0 of the UniProt.ws (on R version 3.5.2), this returns:
        HGNC         ENSEMBL
1   HGNC:417 ENSG00000136872
2 HGNC:30235            NA
3 HGNC:19732            NA
4       NA            NA
5       NA            NA
6       NA            NA

Why is the result NA for HGNC:30235 and HGNC:19732? These HGNC IDs are linked to Ensembl genes by HGNC. And why are HGNC IDs 51504, 51514, and 51513 returned as NA's? These are valid HGNC IDs.

**Comment by Kayla-Morrell** [comment]
UniProt.ws is a package that retrieves data from the UniProt web service, which can be found [here](https://www.uniprot.org/). If you search the 'HGNC:30235' and 'HGNC:19732' ids on the web service, you will see entries but there is no information about the ENSEMBL id. This would make sense as to why the function reports back NA for those ids. If you search the 'HGNC:51504', 'HGNC:51514', and 'HGNC:51513' ids on the web service, no results will come back which is why the function returned NA's.
